drop table if exists vendorquery;
drop table if exists components;
drop table if exists vendor;
drop table if exists bom;
drop table if exists users;



CREATE TABLE Users(
	UserID INTEGER AUTO_INCREMENT PRIMARY KEY,
	Email VARCHAR(250) NOT NULL,
	Password VARCHAR(500),
	isAdmin BOOLEAN NOT NULL,
	isLocked BOOLEAN NOT NULL,
	isApproved BOOLEAN NOT NULL,
	CreateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	DeleteDate DATETIME
	);

CREATE TABLE BOM(
	BOM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	UserID INTEGER NOT NULL,
	BOM_Title VARCHAR(50) NOT NULL,
	CreateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	DeleteDate DATETIME,
	CONSTRAINT UserID_fk FOREIGN KEY(UserID) REFERENCES Users(UserID));

CREATE TABLE Vendor(
	VendorID INTEGER AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(50),
	CreateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	DeleteDate DATETIME,
	QueryDate DATETIME
	);

CREATE TABLE VendorQuery(
	VendorQueryID INTEGER AUTO_INCREMENT PRIMARY KEY,
	VendorID INTEGER NOT NULL,
	BOM_ID INTEGER NOT NULL,
	QueryDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	CONSTRAINT VendorID_fk FOREIGN KEY(VendorID) REFERENCES Vendor(VendorID),
	CONSTRAINT BOM_ID_fk FOREIGN KEY(BOM_ID) REFERENCES BOM(BOM_ID)
	);

CREATE TABLE Components(
	ComponentID INTEGER AUTO_INCREMENT PRIMARY KEY,
	BOM_ID INTEGER,
	VendorID INTEGER,
	PartNumber VARCHAR(20) NOT NULL,
	UserDescription VARCHAR(100) NOT NULL,
       VendorDescription VARCHAR(100),
	Price DECIMAL(13,4),
	Quantity INTEGER,
	QuantityAvailable INTEGER,
	CreateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	DeleteDate DATETIME,
	CONSTRAINT BOM_ID_fk2 FOREIGN KEY(BOM_ID) REFERENCES BOM(BOM_ID),
	CONSTRAINT VendorID_fk2 FOREIGN KEY(VendorID) REFERENCES Vendor(VendorID)
	);

